import 'package:flutter/material.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedRoastedchickenriceWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedCircleWidget2.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedTomsfavouritefoodWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedImage32Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedImage33Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedCircleWidget1.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedGroup16292Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedChashuRiceWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedPaybuttonWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/Generated\$5Widget1.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/Generated\$450Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedBackWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedSteamedChickenRiceWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedPleaseselectamealtodonateWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedGroup16294Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedCircleWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedmerchantpage2widget/generated/GeneratedFinalStateWidget.dart';

/* Frame Merchant Page 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMerchantPage2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedPaymentPageWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 89.0,
                  top: 57.0,
                  right: null,
                  bottom: null,
                  width: 255.0,
                  height: 15.0,
                  child: GeneratedTomsfavouritefoodWidget(),
                ),
                Positioned(
                  left: 36.0,
                  top: 103.0,
                  right: null,
                  bottom: null,
                  width: 279.0,
                  height: 76.0,
                  child: GeneratedPleaseselectamealtodonateWidget(),
                ),
                Positioned(
                  left: 8.0,
                  top: 32.0,
                  right: null,
                  bottom: null,
                  width: 57.0,
                  height: 63.0,
                  child: GeneratedBackWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 584.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 56.0,
                  child: GeneratedGroup16292Widget(),
                ),
                Positioned(
                  left: 13.0,
                  top: 289.0,
                  right: null,
                  bottom: null,
                  width: 97.0,
                  height: 85.20270538330078,
                  child: GeneratedImage32Widget(),
                ),
                Positioned(
                  left: 55.0,
                  top: 524.0,
                  right: null,
                  bottom: null,
                  width: 250.0,
                  height: 47.311790466308594,
                  child: GeneratedPaybuttonWidget(),
                ),
                Positioned(
                  left: 11.0,
                  top: 409.0,
                  right: null,
                  bottom: null,
                  width: 97.0,
                  height: 85.19999694824219,
                  child: GeneratedImage33Widget(),
                ),
                Positioned(
                  left: 8.0,
                  top: 112.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 142.0,
                  child: GeneratedGroup16294Widget(),
                ),
                Positioned(
                  left: 120.0,
                  top: 320.0,
                  right: null,
                  bottom: null,
                  width: 26.0,
                  height: 24.0,
                  child: Generated$5Widget1(),
                ),
                Positioned(
                  left: 122.0,
                  top: 438.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 24.0,
                  child: Generated$450Widget(),
                ),
                Positioned(
                  left: 112.0,
                  top: 174.0,
                  right: null,
                  bottom: null,
                  width: 232.0,
                  height: 38.0,
                  child: GeneratedSteamedChickenRiceWidget(),
                ),
                Positioned(
                  left: 114.0,
                  top: 297.0,
                  right: null,
                  bottom: null,
                  width: 232.0,
                  height: 38.0,
                  child: GeneratedRoastedchickenriceWidget(),
                ),
                Positioned(
                  left: 116.0,
                  top: 416.0,
                  right: null,
                  bottom: null,
                  width: 232.0,
                  height: 38.0,
                  child: GeneratedChashuRiceWidget(),
                ),
                Positioned(
                  left: 313.0,
                  top: 444.0,
                  right: null,
                  bottom: null,
                  width: 30.0,
                  height: 30.0,
                  child: GeneratedCircleWidget(),
                ),
                Positioned(
                  left: 313.0,
                  top: 321.0,
                  right: null,
                  bottom: null,
                  width: 30.0,
                  height: 30.0,
                  child: GeneratedCircleWidget1(),
                ),
                Positioned(
                  left: 314.0,
                  top: 204.0,
                  right: null,
                  bottom: null,
                  width: 30.0,
                  height: 30.0,
                  child: GeneratedCircleWidget2(),
                ),
                Positioned(
                  left: 314.0,
                  top: 204.0,
                  right: null,
                  bottom: null,
                  width: 30.0,
                  height: 30.0,
                  child: GeneratedFinalStateWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
