import 'package:flutter/material.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentconfirmationwidget/generated/Generated69Widget2.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentconfirmationwidget/generated/GeneratedSignalcellularaltWidget2.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentconfirmationwidget/generated/GeneratedBatterychargingfullWidget2.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentconfirmationwidget/generated/GeneratedSignalwifi4barWidget2.dart';

/* Group Group 90
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup90Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 64.0,
      height: 12.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        Positioned(
          left: 39.0,
          top: 1.0,
          right: null,
          bottom: null,
          width: 30.0,
          height: 15.0,
          child: Generated69Widget2(),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: null,
          bottom: null,
          width: 10.629938125610352,
          height: 12.0,
          child: GeneratedSignalwifi4barWidget2(),
        ),
        Positioned(
          left: 25.689453125,
          top: 0.0,
          right: null,
          bottom: null,
          width: 10.629938125610352,
          height: 12.0,
          child: GeneratedBatterychargingfullWidget2(),
        ),
        Positioned(
          left: 12.84375,
          top: 0.0,
          right: null,
          bottom: null,
          width: 10.629938125610352,
          height: 12.0,
          child: GeneratedSignalcellularaltWidget2(),
        )
      ]),
    );
  }
}
