import 'package:flutter/material.dart';

/* Text Back to Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBacktoHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.center,
      child: Text(
        '''Back to Home''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.171875,
          fontSize: 20.0,
          fontFamily: 'Montserrat',
          fontWeight: FontWeight.w800,
          color: Color.fromARGB(255, 255, 255, 255),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
