import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget32 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 6.426490306854248,
      height: 42.03240966796875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M6.42649 3.18565L6.42649 38.8468C6.42649 40.6072 4.99963 42.0324 3.23921 42.0324L0 42.0324C1.76042 42.0324 3.18728 40.6072 3.18728 38.8468L3.18728 3.18565C3.18728 1.42523 1.76042 1.39441e-08 0 1.39441e-08L3.23905 1.39441e-08C4.99963 -0.000162777 6.42649 1.42507 6.42649 3.18565L6.42649 3.18565Z')
          ..color = Color.fromARGB(255, 9, 167, 109),
      ]),
    );
  }
}
