import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget43 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 19.43477439880371,
      height: 6.126954555511475,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M19.4348 4.50735C19.4348 5.07907 19.3295 5.62491 19.1335 6.12695C18.4841 4.43767 16.8449 3.23921 14.9274 3.23921L4.50719 3.23921C3.26331 3.23921 2.13614 3.74451 1.31991 4.55912C0.877768 5.00126 0.527931 5.53244 0.301164 6.12679C0.105164 5.62474 0 5.07891 0 4.50719C0 3.26168 0.503675 2.13614 1.31991 1.31991C2.13614 0.505303 3.26331 0 4.50719 0L14.9274 0C17.4167 0.000162791 19.4348 2.01812 19.4348 4.50735Z')
          ..color = Color.fromARGB(255, 234, 155, 88),
      ]),
    );
  }
}
