import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget40 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 19.435096740722656,
      height: 9.014050483703613,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M14.9281 9.01405L4.50702 9.01405C2.01779 9.01405 0 6.9961 0 4.50703C0 2.01779 2.01795 0 4.50702 0L14.9281 0C17.4173 0 19.4351 2.01795 19.4351 4.50703C19.4351 6.9961 17.4173 9.01405 14.9281 9.01405Z')
          ..color = Color.fromARGB(255, 246, 169, 108),
      ]),
    );
  }
}
