import 'package:flutter/material.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentconfirmationwidget/generated/GeneratedImage31Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentconfirmationwidget/generated/GeneratedThankYouWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentconfirmationwidget/generated/GeneratedPaybuttonWidget3.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentconfirmationwidget/generated/GeneratedLeftarrow2Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentconfirmationwidget/generated/GeneratedGroup16275Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentconfirmationwidget/generated/GeneratedThankyouforthemealourbeneficiarieswillreallyappreciatei.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentconfirmationwidget/generated/GeneratedGroup16292Widget3.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentconfirmationwidget/generated/GeneratedGroupWidget3.dart';

/* Frame Payment confirmation
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaymentconfirmationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedHomepageWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 29.0,
                  top: 222.0,
                  right: null,
                  bottom: null,
                  width: 323.0,
                  height: 175.0,
                  child:
                      GeneratedThankyouforthemealourbeneficiarieswillreallyappreciatei(),
                ),
                Positioned(
                  left: -433.0,
                  top: -56.0,
                  right: null,
                  bottom: null,
                  width: 27.0,
                  height: 27.0,
                  child: GeneratedLeftarrow2Widget(),
                ),
                Positioned(
                  left: 138.0,
                  top: 119.0,
                  right: null,
                  bottom: null,
                  width: 84.0,
                  height: 84.0,
                  child: GeneratedImage31Widget(),
                ),
                Positioned(
                  left: -2.0,
                  top: -63.0,
                  right: null,
                  bottom: null,
                  width: 309.0,
                  height: 20.0,
                  child: GeneratedGroup16275Widget(),
                ),
                Positioned(
                  left: 110.0,
                  top: 45.0,
                  right: null,
                  bottom: null,
                  width: 148.0,
                  height: 29.0,
                  child: GeneratedThankYouWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.2313237296210395;

                    final double height = constraints.maxHeight * 0.1296875;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.3888888888888889,
                          y: constraints.maxHeight * 0.5984375,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget3(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 57.0,
                  top: 523.0,
                  right: null,
                  bottom: null,
                  width: 250.0,
                  height: 47.311790466308594,
                  child: GeneratedPaybuttonWidget3(),
                ),
                Positioned(
                  left: 0.0,
                  top: 584.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 56.0,
                  child: GeneratedGroup16292Widget3(),
                )
              ]),
        ),
      ),
    ));
  }
}
