import 'package:flutter/material.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedRectangle6609Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedMrTomWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedDinnerWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedRectangle6610Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedDescriptionWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedRectangle6611Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedLine48Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedMynameisTomIhaveworkedforaconstructioncompanyforover20y.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedGroup16293Widget1.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/Generated1957Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedRectangle6606Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedGroup16293Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedLine48Widget1.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedLunchWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedRectangle6607Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedRectangle6608Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedBreakfastWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedBuymeamealWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedspecificbeneficiarywidget/generated/GeneratedBackWidget3.dart';

/* Frame Specific Beneficiary
    Autogenerated by GoogleIgniteGrp5 FTF Generator
  */
class GeneratedSpecificBeneficiaryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedMerchantPage2Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 296.0,
                  child: GeneratedRectangle6606Widget(),
                ),
                Positioned(
                  left: 25.0,
                  top: 15.0,
                  right: null,
                  bottom: null,
                  width: 309.0,
                  height: 20.0,
                  child: GeneratedGroup16293Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 271.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 369.0,
                  child: GeneratedRectangle6607Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 584.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 56.0,
                  child: GeneratedGroup16293Widget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 584.0465087890625,
                  right: null,
                  bottom: null,
                  width: 360.00140380859375,
                  height: 1.0,
                  child: GeneratedLine48Widget(),
                ),
                Positioned(
                  left: 27.0,
                  top: 307.0,
                  right: null,
                  bottom: null,
                  width: 78.0,
                  height: 2.0,
                  child: GeneratedMrTomWidget(),
                ),
                Positioned(
                  left: 291.0,
                  top: 307.0,
                  right: null,
                  bottom: null,
                  width: 49.0,
                  height: 5.0,
                  child: Generated1957Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 328.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 256.0,
                  child: GeneratedRectangle6608Widget(),
                ),
                Positioned(
                  left: 25.0,
                  top: 347.0,
                  right: null,
                  bottom: null,
                  width: 91.0,
                  height: 5.0,
                  child: GeneratedDescriptionWidget(),
                ),
                Positioned(
                  left: 25.0,
                  top: 362.0,
                  right: null,
                  bottom: null,
                  width: 312.0,
                  height: 118.0,
                  child:
                      GeneratedMynameisTomIhaveworkedforaconstructioncompanyforover20y(),
                ),
                Positioned(
                  left: 25.0,
                  top: 498.0,
                  right: null,
                  bottom: null,
                  width: 106.0,
                  height: 2.0,
                  child: GeneratedBuymeamealWidget(),
                ),
                Positioned(
                  left: 26.0,
                  top: 516.0,
                  right: null,
                  bottom: null,
                  width: 93.0,
                  height: 42.0,
                  child: GeneratedRectangle6609Widget(),
                ),
                Positioned(
                  left: 133.0,
                  top: 516.0,
                  right: null,
                  bottom: null,
                  width: 94.0,
                  height: 42.0,
                  child: GeneratedRectangle6610Widget(),
                ),
                Positioned(
                  left: 241.0,
                  top: 516.0,
                  right: null,
                  bottom: null,
                  width: 93.0,
                  height: 42.0,
                  child: GeneratedRectangle6611Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 576.0465087890625,
                  right: null,
                  bottom: null,
                  width: 360.00140380859375,
                  height: 1.0,
                  child: GeneratedLine48Widget1(),
                ),
                Positioned(
                  left: 44.0,
                  top: 537.0,
                  right: null,
                  bottom: null,
                  width: 62.0,
                  height: 5.0,
                  child: GeneratedBreakfastWidget(),
                ),
                Positioned(
                  left: 162.0,
                  top: 537.0,
                  right: null,
                  bottom: null,
                  width: 40.0,
                  height: 5.0,
                  child: GeneratedLunchWidget(),
                ),
                Positioned(
                  left: 269.0,
                  top: 537.0,
                  right: null,
                  bottom: null,
                  width: 43.0,
                  height: 5.0,
                  child: GeneratedDinnerWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 41.0,
                  right: null,
                  bottom: null,
                  width: 57.0,
                  height: 63.0,
                  child: GeneratedBackWidget3(),
                )
              ]),
        ),
      ),
    ));
  }
}
