import 'package:flutter/material.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentdetailspagewidget/generated/GeneratedCardNumberWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentdetailspagewidget/generated/Generated0000000000000000Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentdetailspagewidget/generated/GeneratedGroup16274Widget1.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentdetailspagewidget/generated/GeneratedBackWidget2.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentdetailspagewidget/generated/GeneratedCheckyouremailtoconfirmpaymentfromyourBankWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentdetailspagewidget/generated/GeneratedCVVWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentdetailspagewidget/generated/GeneratedExpiryDateWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentdetailspagewidget/generated/GeneratedGroup16292Widget2.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentdetailspagewidget/generated/GeneratedFrame15Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentdetailspagewidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentdetailspagewidget/generated/GeneratedPaymentdetailsWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentdetailspagewidget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentdetailspagewidget/generated/GeneratedPaybuttonWidget2.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentdetailspagewidget/generated/GeneratedMastercardLogoWidget.dart';

/* Frame Payment details page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaymentdetailspageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: -56.0,
            right: null,
            bottom: null,
            width: 309.0,
            height: 20.0,
            child: GeneratedGroup16274Widget1(),
          ),
          Positioned(
            left: 72.0,
            top: 44.0,
            right: null,
            bottom: null,
            width: 204.0,
            height: 29.0,
            child: GeneratedPaymentdetailsWidget(),
          ),
          Positioned(
            left: 8.0,
            top: 32.0,
            right: null,
            bottom: null,
            width: 57.0,
            height: 63.0,
            child: GeneratedBackWidget2(),
          ),
          Positioned(
            left: 28.0,
            top: 127.0,
            right: null,
            bottom: null,
            width: 130.0,
            height: 23.0,
            child: GeneratedPaymentdetailspageWidget(),
          ),
          Positioned(
            left: 16.0,
            top: 148.0,
            right: null,
            bottom: null,
            width: 333.0,
            height: 46.0,
            child: GeneratedRectangle24Widget(),
          ),
          Positioned(
            left: 35.0,
            top: 161.0,
            right: null,
            bottom: null,
            width: 234.0,
            height: 20.0,
            child: Generated0000000000000000Widget(),
          ),
          Positioned(
            left: 290.0,
            top: 154.0,
            right: null,
            bottom: null,
            width: 47.0,
            height: 29.0,
            child: GeneratedMastercardLogoWidget(),
          ),
          Positioned(
            left: 18.7750244140625,
            top: 206.48207092285156,
            right: null,
            bottom: null,
            width: 330.2250061035156,
            height: 71.95217895507812,
            child: GeneratedCardNumberWidget(),
          ),
          Positioned(
            left: 18.7750244140625,
            top: 295.1673278808594,
            right: null,
            bottom: null,
            width: 154.3776397705078,
            height: 72.7888412475586,
            child: GeneratedExpiryDateWidget(),
          ),
          Positioned(
            left: 197.689453125,
            top: 297.67730712890625,
            right: null,
            bottom: null,
            width: 151.31053161621094,
            height: 72.7888412475586,
            child: GeneratedCVVWidget(),
          ),
          Positioned(
            left: 87.0,
            top: 436.0,
            right: null,
            bottom: null,
            width: 195.0,
            height: 38.0,
            child: GeneratedCheckyouremailtoconfirmpaymentfromyourBankWidget(),
          ),
          Positioned(
            left: 0.0,
            top: 584.0,
            right: null,
            bottom: null,
            width: 360.0,
            height: 56.0,
            child: GeneratedGroup16292Widget2(),
          ),
          Positioned(
            left: 24.0,
            top: 501.0,
            right: null,
            bottom: null,
            width: 151.0,
            height: 24.0,
            child: GeneratedGroup7Widget(),
          ),
          Positioned(
            left: 40.0,
            top: 537.0,
            right: null,
            bottom: null,
            width: 279.0,
            height: 47.311790466308594,
            child: GeneratedPaybuttonWidget2(),
          ),
          Positioned(
            left: 25.0,
            top: 381.0,
            right: null,
            bottom: null,
            width: 104.0,
            height: 19.0,
            child: GeneratedFrame15Widget(),
          )
        ]),
      ),
    ));
  }
}
