import 'package:flutter/material.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedPaybuttonWidget1.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedGroup16288Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedGroup16287Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedIcontrash2Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedSteamedChickenRice\$5Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedGroup16274Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedGroup16286Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedBackWidget1.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedGroup16292Widget1.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedGroup16290Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedCheckoutWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedSelectPaymentMethodWidget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedGroup16291Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedScreenshot202209231458592Widget.dart';
import 'package:flutterapp/zerohungerappapp/generatedpaymentpagewidget/generated/GeneratedRectangle11Widget.dart';

/* Frame Payment Page
    Autogenerated by GoogleIgniteGrp5 FTF Generator
  */
class GeneratedPaymentPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedPaymentdetailspageWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 27.0,
                  top: 9.0,
                  right: null,
                  bottom: null,
                  width: 309.0,
                  height: 20.0,
                  child: GeneratedGroup16274Widget(),
                ),
                Positioned(
                  left: 45.0,
                  top: 165.0,
                  right: null,
                  bottom: null,
                  width: 276.0,
                  height: 74.0,
                  child: GeneratedRectangle11Widget(),
                ),
                Positioned(
                  left: 22.0,
                  top: 212.0,
                  right: null,
                  bottom: null,
                  width: 223.0,
                  height: 29.0,
                  child: GeneratedSelectPaymentMethodWidget(),
                ),
                Positioned(
                  left: 8.0,
                  top: 32.0,
                  right: null,
                  bottom: null,
                  width: 57.0,
                  height: 63.0,
                  child: GeneratedBackWidget1(),
                ),
                Positioned(
                  left: 70.0,
                  top: 50.0,
                  right: null,
                  bottom: null,
                  width: 258.0,
                  height: 18.0,
                  child: GeneratedCheckoutWidget(),
                ),
                Positioned(
                  left: 22.0,
                  top: 239.0,
                  right: null,
                  bottom: null,
                  width: 317.0,
                  height: 78.0,
                  child: GeneratedGroup16290Widget(),
                ),
                Positioned(
                  left: 24.0,
                  top: 315.0,
                  right: null,
                  bottom: null,
                  width: 317.0,
                  height: 64.0,
                  child: GeneratedGroup16287Widget(),
                ),
                Positioned(
                  left: 22.0,
                  top: 331.0,
                  right: null,
                  bottom: null,
                  width: 317.0,
                  height: 139.0,
                  child: GeneratedGroup16288Widget(),
                ),
                Positioned(
                  left: 22.0,
                  top: 469.0,
                  right: null,
                  bottom: null,
                  width: 317.0,
                  height: 64.0,
                  child: GeneratedGroup16291Widget(),
                ),
                Positioned(
                  left: 22.0,
                  top: 95.0,
                  right: null,
                  bottom: null,
                  width: 117.0,
                  height: 96.0,
                  child: GeneratedScreenshot202209231458592Widget(),
                ),
                Positioned(
                  left: 151.0,
                  top: 96.0,
                  right: null,
                  bottom: null,
                  width: 232.0,
                  height: 38.0,
                  child: GeneratedSteamedChickenRice$5Widget(),
                ),
                Positioned(
                  left: 151.0,
                  top: 157.0,
                  right: null,
                  bottom: null,
                  width: 116.0,
                  height: 30.0,
                  child: GeneratedGroup16286Widget(),
                ),
                Positioned(
                  left: 311.0,
                  top: 162.0,
                  right: null,
                  bottom: null,
                  width: 20.0,
                  height: 20.0,
                  child: GeneratedIcontrash2Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 584.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 56.0,
                  child: GeneratedGroup16292Widget1(),
                ),
                Positioned(
                  left: 57.0,
                  top: 537.0,
                  right: null,
                  bottom: null,
                  width: 250.0,
                  height: 47.31179428100586,
                  child: GeneratedPaybuttonWidget1(),
                )
              ]),
        ),
      ),
    ));
  }
}
